abstractqqq/polars_ds_extension

- python/polars_ds/extensions.py
Specify what it's a standard error for and that it's only an estimate of that quantity.
> Change statistical description of standard error

- Cargo.toml
- README.md
- pyproject.toml
- python/polars_ds/extensions.py
- src/lib.rs
- src/num_ext/jaccard.rs
- src/num_ext/ols.rs
- tests/test.ipynb
- tests/test_ext.py
1. Added list jaccard
2. Added more str manipulation expressions
> More features and prepare for v.0.1.1 release

- .gitignore
- python/polars_ds/__init__.py
- python/polars_ds/complex_ext.py
- python/polars_ds/num_ext.py
- python/polars_ds/stats_ext.py
- python/polars_ds/str_ext.py
- python/polars_ds/type_alias.py
- src/num_ext/complex.rs
- src/num_ext/fft.rs
- src/num_ext/mod.rs
- tests/test.ipynb
1. Added basic complex number operations
2. Added detrend using either linear or mean method
> basic complex + detrend

- python/polars_ds/num_ext.py
- python/polars_ds/stats_ext.py
- src/num_ext/tp_fp.rs
- src/stats_ext/sample.rs
- src/str_ext/levenshtein.rs
- tests/test.ipynb
Added sampling from binomial and exponential distribution
> added binomial and exp

- Cargo.lock
- Cargo.toml
- README.md
- docs/index.md
- examples/basics.ipynb
- pyproject.toml
- python/polars_ds/__init__.py
- python/polars_ds/num_ext.py
- python/polars_ds/stats_ext.py
- python/polars_ds/str_ext.py
- src/str_ext/aho_corasick.rs
- src/str_ext/fuzz.rs
- src/str_ext/inflections.rs
- src/str_ext/mod.rs
- tests/test.ipynb
- tests/test_ext.py
added some str inflections, LCS based freq from rapidfuzz
> added some str inflections, LCS based freq from rapidfuzz

- .github/workflows/CI.yml
- .gitignore
- python/polars_ds/__init__.py
- python/polars_ds/num_ext.py
- python/polars_ds/stats_ext.py
- requirements.txt
- src/num_ext/lempel_ziv.rs
- src/num_ext/mod.rs
- src/stats_ext/ks.rs
- tests/requirements-test.txt
- tests/test.ipynb
- tests/test_ext.py
- tests/test_memory.py
added lempel_ziv for boolean columns
> added lempel ziv

- examples/basics.ipynb
- python/polars_ds/str2.py
- src/num_ext/entrophies.rs
- src/num_ext/knn.rs
- src/num_ext/tp_fp.rs
- src/stats_ext/chi2.rs
- src/stats_ext/fstats.rs
- tests/test.ipynb
Fixed bug for chi2 in group by context.
> Debug chi2

- Cargo.lock
- Cargo.toml
- pyproject.toml
- python/polars_ds/__init__.py
- src/num_ext/cond_entropy.rs
- src/num_ext/entrophies.rs
- src/num_ext/knn.rs
- tests/test.ipynb
1. Fixed a bug in group_by context for distances
> fixed group by problem

- examples/basics.ipynb
- python/polars_ds/num.py
- src/lib.rs
- src/num/entrophies.rs
- src/num/knn.rs
- src/num/ols.rs
- src/stats/t_test.rs
- tests/test.ipynb
1. Fixed lstsq's problem in rolling context
> Better ols

- python/polars_ds/num.py
- src/num/mod.rs
- src/num/woe_iv.rs
- tests/test.ipynb
1. weight of evidence and information value
> Information value

- src/num/jaccard.rs
- src/num/logit_expit_gamma.rs
- tests/test.ipynb
> Less casting

- examples/basics.ipynb
- pyproject.toml
- python/polars_ds/__init__.py
- python/polars_ds/graph.py
- python/polars_ds/num.py
- src/graph/eigen_centrality.rs
- src/graph/mod.rs
- src/lib.rs
- src/num/knn.rs
- src/num/mod.rs
- src/num/ols.rs
- tests/test.ipynb
- tests/test_ext.py
> Add cosine

- python/polars_ds/stats.py
1. added w_mean, w_var and ttest_ind_from_stats
> added more simple stats

- CONTRIBUTING.md
- README.md
- examples/basics.ipynb
- tests/test.ipynb
- tests/test_ext.py
1. Improve readme, contrib, and added one test and example
> more tests and examples

- .gitignore
- .pre-commit-config.yaml
- Cargo.lock
- Cargo.toml
- pyproject.toml
- python/polars_ds/__init__.py
- python/polars_ds/complex.py
- src/num/fft.rs
- tests/test.ipynb
- tests/test_ext.py
Complex numbers should be arr[f64, 2] to suggest immutable length. Also changed rfft output to be arr[f64, 2]
> Refactor c

- .gitignore
- .pre-commit-config.yaml
- Cargo.lock
- Cargo.toml
- examples/basics.ipynb
- pyproject.toml
- python/polars_ds/__init__.py
- python/polars_ds/complex.py
- python/polars_ds/graph.py
- src/graph/mod.rs
- src/graph/shortest_path.rs
- src/num/fft.rs
- tests/test.ipynb
- tests/test_ext.py
Implemented using Dijkstra in petgraph.
Essentially another shortest path algorithm that returns only (1) whether it is reachable (2) Distance assuming constant cost. However, this is way faster to compute so is better to use this as a filter
> Added "reachability" for graph

- python/polars_ds/metrics.py
- python/polars_ds/type_alias.py
- tests/test.ipynb
- tests/test_correctness.py
> added multiclass rocauc

- Cargo.toml
- src/num/ols.rs
- tests/test.ipynb
> faster ols

- examples/transfer_entropy.ipynb
- python/polars_ds/num.py
- tests/test_knn_entropy.py
> NumExt : add Transfer Entropy and related measures

- README.md
> Pretty Code Snippets

- examples/basics.ipynb
- python/polars_ds/expr_linear.py
- src/num_ext/linear_regression.rs
Coefficient output was length n (a struct scalar repeated n times), but should be 1. since this should be a scalar
> fixed the output size of multitarget linreg

- python/polars_ds/_utils.py
- python/polars_ds/eda/diagnosis.py
- python/polars_ds/exprs/expr_knn.py
- python/polars_ds/exprs/expr_linear.py
- python/polars_ds/exprs/metrics.py
- python/polars_ds/exprs/num.py
- python/polars_ds/modeling/_structures.py
- python/polars_ds/modeling/pipeline.py
- python/polars_ds/partition/partition.py
- tests/test_compat.py
I tried to take care of some of the things my linter was complaining about. Some of these are autofixes and some manual.
> various typing fixes

- python/polars_ds/exprs/metrics.py
- tests/test_metrics.py
This PR introduces a high-performance NDCG implementation for Polars, providing a crucial ranking evaluation metric for search and recommendation systems. The implementation matches scikit-learn's NDCG scores while leveraging Polars' efficient data processing capabilities.
- 🚀 **High Performance**: Leverages Polars' native operations for efficient computation
- 🔄 **Tie Handling**: Supports both sequential and averaged handling of tied scores
- 🎯 **Top-K Evaluation**: Configurable cutoff for evaluating top-K items
- 📊 **Group-wise Processing**: Efficiently handles multiple queries/users simultaneously
- ✅ **Verified Accuracy**: Matches scikit-learn's implementation exactly
- Search engine result ranking evaluation
- Recommendation system performance measurement
- Learning to rank model …
> Add NDCG implementation; fixes ##346

- README.md
- python/polars_ds/exprs/expr_linear.py
- src/linear/lr/lr_solvers.rs
- src/num_ext/linear_regression.rs
- src/num_ext/linear_regression_f32.rs
- tests/test_many.py
Use `positive = True` in `pds.lin_reg` for non-negative linear regression
> Nonneg linear reg
